# 默认页面配置（请勿直接修改）。
# 建议复制到 config/user/pages/otherguide.yml 并按需调整。
title: 其他导航网站           # 页面标题
subtitle: 其他导航网站  # 页面副标题

# 指定使用的模板文件名，现有页面模板可见 templates/pages（不含 .hbs）
template: otherguide


# 页面分类与站点列表
categories:
  - name: AI工具集
    icon: fab fa-google # 微信图标
    sites:
      - name: AI工具集
        url: https://ai-bot.cn/
        icon: fab fa-ai-bot
        description: AI工具集导航网站

