# 默认页面配置（请勿直接修改）。
# 建议复制到 config/user/pages/wechat.yml 并按需调整。
title: 公众号           # 页面标题
subtitle: 公众号运营所需工具 # 页面副标题

# 指定使用的模板文件名，现有页面模板可见 templates/pages（不含 .hbs）
template: wechat

# 页面分类与站点列表
categories:
  - name: 运营工具
    icon: fab fa-weixin # 微信图标
    sites:
      - name: 微信公众平台
        icon: fas fa-comment-dots
        description: 微信公众号官方后台，文章发布与管理
        url: https://mp.weixin.qq.com/
      - name: Doocs MD
        icon: fab fa-markdown
        description: 开源、简洁的微信 Markdown 编辑器
        url: https://md.doocs.org/
      - name: mdnice
        icon: fas fa-pen-nib
        description: 支持自定义主题的 Markdown 排版工具
        url: https://www.mdnice.com/
      - name: 壹伴助手
        icon: fas fa-puzzle-piece
        description: 强大的公众号运营浏览器插件
        url: https://yiban.io/
      - name: 秀米编辑器
        icon: fas fa-layer-group
        description: 专业的图文排版工具，布局丰富
        url: https://xiumi.us/

  - name: 数据与素材
    icon: fas fa-chart-line # 图表图标
    sites:
      - name: 新榜
        icon: fas fa-chart-bar
        description: 新媒体数据监测与排行榜
        url: https://www.newrank.cn/
      - name: 西瓜数据
        icon: fas fa-chart-pie
        description: 公众号诊断与数据分析平台
        url: http://data.xiguaji.com/
      - name: 稿定设计
        icon: fas fa-palette
        description: 快速制作公众号封面与配图
        url: https://www.gaoding.com/
      - name: 阿里巴巴矢量库
        icon: fas fa-icons
        description: 免费且丰富的矢量图标库 (Iconfont)
        url: https://www.iconfont.cn/
      - name: Unsplash
        icon: fas fa-camera
        description: 全球知名的免费无版权高清图片库
        url: https://unsplash.com/

  - name: 协作与效率
    icon: fas fa-rocket # 火箭图标
    sites:
      - name: 飞书云文档
        icon: fas fa-file-alt
        description: 高效的团队协作与文档管理工具
        url: https://f0txvtlyswr.feishu.cn/drive/home/
      - name: 草料二维码
        icon: fas fa-qrcode
        description: 快速生成与美化二维码
        url: https://cli.im/
      - name: 金数据
        icon: fas fa-poll-h
        description: 问卷调查与表单收集工具
        url: https://jinshuju.net/
